/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface XyzLink {
      'download': string;
      'href': string;
      'hreflang': string;
      'rel': string;
      'target': string;
      'to': string;
    }

    interface XyzTextField {
      'disabled': boolean;
      'errorText': string;
      'getInput': () => HTMLInputElement;
      'getLabel': () => HTMLElement;
      'helperText': string;
      'label': string;
      'placeholder': string;
      'required': boolean;
      'value': string;
    }

    interface XyzTypographyCaption {

    }

    interface XyzTypographyHeadline {
      'level': number;
    }

    interface XyzTypographyParagraph {

    }
  }


    interface HTMLXyzLinkElement extends StencilComponents.XyzLink, HTMLStencilElement {}

    var HTMLXyzLinkElement: {
      prototype: HTMLXyzLinkElement;
      new (): HTMLXyzLinkElement;
    };
    

    interface HTMLXyzTextFieldElement extends StencilComponents.XyzTextField, HTMLStencilElement {}

    var HTMLXyzTextFieldElement: {
      prototype: HTMLXyzTextFieldElement;
      new (): HTMLXyzTextFieldElement;
    };
    

    interface HTMLXyzTypographyCaptionElement extends StencilComponents.XyzTypographyCaption, HTMLStencilElement {}

    var HTMLXyzTypographyCaptionElement: {
      prototype: HTMLXyzTypographyCaptionElement;
      new (): HTMLXyzTypographyCaptionElement;
    };
    

    interface HTMLXyzTypographyHeadlineElement extends StencilComponents.XyzTypographyHeadline, HTMLStencilElement {}

    var HTMLXyzTypographyHeadlineElement: {
      prototype: HTMLXyzTypographyHeadlineElement;
      new (): HTMLXyzTypographyHeadlineElement;
    };
    

    interface HTMLXyzTypographyParagraphElement extends StencilComponents.XyzTypographyParagraph, HTMLStencilElement {}

    var HTMLXyzTypographyParagraphElement: {
      prototype: HTMLXyzTypographyParagraphElement;
      new (): HTMLXyzTypographyParagraphElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'xyz-link': JSXElements.XyzLinkAttributes;
    'xyz-text-field': JSXElements.XyzTextFieldAttributes;
    'xyz-typography-caption': JSXElements.XyzTypographyCaptionAttributes;
    'xyz-typography-headline': JSXElements.XyzTypographyHeadlineAttributes;
    'xyz-typography-paragraph': JSXElements.XyzTypographyParagraphAttributes;
    }
  }

  namespace JSXElements {

    export interface XyzLinkAttributes extends HTMLAttributes {
      'download'?: string;
      'href'?: string;
      'hreflang'?: string;
      'rel'?: string;
      'target'?: string;
      'to'?: string;
    }

    export interface XyzTextFieldAttributes extends HTMLAttributes {
      'disabled'?: boolean;
      'errorText'?: string;
      'helperText'?: string;
      'label'?: string;
      'placeholder'?: string;
      'required'?: boolean;
      'value'?: string;
    }

    export interface XyzTypographyCaptionAttributes extends HTMLAttributes {

    }

    export interface XyzTypographyHeadlineAttributes extends HTMLAttributes {
      'level'?: number;
    }

    export interface XyzTypographyParagraphAttributes extends HTMLAttributes {

    }
  }

  interface HTMLElementTagNameMap {
    'xyz-link': HTMLXyzLinkElement
    'xyz-text-field': HTMLXyzTextFieldElement
    'xyz-typography-caption': HTMLXyzTypographyCaptionElement
    'xyz-typography-headline': HTMLXyzTypographyHeadlineElement
    'xyz-typography-paragraph': HTMLXyzTypographyParagraphElement
  }

  interface ElementTagNameMap {
    'xyz-link': HTMLXyzLinkElement;
    'xyz-text-field': HTMLXyzTextFieldElement;
    'xyz-typography-caption': HTMLXyzTypographyCaptionElement;
    'xyz-typography-headline': HTMLXyzTypographyHeadlineElement;
    'xyz-typography-paragraph': HTMLXyzTypographyParagraphElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;